### ISSUE TITLE
How to use that?

### ISSUE THREAD

**Issue by Rabbit0x0** [VictorRayan/bip-39_bruteforce_metamask#1]
Hello, how to use that ?

im trying but the error ist always same : 

` python3 bruteForce_Metamask.py
Traceback (most recent call last):
  File "/home/rabbit0x0/Schreibtisch/bip-39_bruteforce_metamask/python/bruteForce_Metamask.py", line 3, in <module>
    import pandas as pd
  File "/usr/lib/python3/dist-packages/pandas/__init__.py", line 52, in <module>
    from pandas.core.api import (
  File "/usr/lib/python3/dist-packages/pandas/core/api.py", line 29, in <module>
    from pandas.core.groupby import Grouper, NamedAgg
  File "/usr/lib/python3/dist-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import DataFrameGroupBy, NamedAgg, SeriesGroupBy
  File "/usr/lib/python3/dist-packages/pandas/core/groupby/generic.py", line 57, in <module>
    from pandas.core.aggregation import (
  File "/usr/lib/python3/dist-packages/pandas/core/aggregation.py", line 26, in <module>
    from pandas.core.indexes.api import Index
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/api.py", line 14, in <module>
    from pandas.core.indexes.category import CategoricalIndex
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/category.py", line 9, in <module>
    from pandas._libs.hashtable import duplicated_int64
ImportError: cannot import name 'duplicated_int64' from 'pandas._libs.hashtable' (/usr/lib/python3/dist-packages/pandas/_libs/hashtable.cpython-310-x86_64-linux-gnu.so)
`

**Comment by VictorRayan** [comment]
After installed libraries correctly, take a look in this readme file
https://github.com/VictorRayan/bip-39_bruteforce_metamask/tree/main/python

**Comment by VictorRayan** [comment]
Hello, you must to install pandas and selenium library correctly.

If you are using Linux O.S, run in terminal the following commands

sudo apt update
sudo pip install pandas
sudo pip install selenium
